deploy:
  provider: surge
  project: "./www/"
  domain: dnam.dk
  on:
    branch: master
env:
  secure: FZydl2OPh8VLm7NMNm5X2LPSvS0TzNNopvbB/jSK7ZWYgpQeYBWW96FiBZ9vU1+sE2vpD59RAgxnJsPIGOo8t+t0r6cqbHQLcmC/5cCAvscXeKt/1vcVUG/ksGSi4icS4qIx8Nsx9eA3ddv3VIYoj2X0BdP/RYz0uw3BUPqPq11QE2JR5SXovhhovh7MLt59xC0IsoWLkx5ZiTrsQRphLZxj4iT7D6A9xRDHfm91J3utyb8zU8vlKA+1U4sEGuyB7Dc4gcPd2xCXKGe+LPqnImwhmAPi+HhEL/2zVOWDTyqdDIZ5B98Fq3FXUkvtsLjUfSkWzKWB4vUp3mBb5g1OxVKAcqPLekqIFyH0DZTmCwJm7bxZe0adYzYFI57snUt7juD5DZJ5G35bTaYepe8jIi2MXuYDyAinix9fpV2p6EeShTKVgolQjUbAgtUX5tWPMDz7DdhP7G91ovZ/20d79NE7riZjbOREP0I0eMY21+opT2IzXIxZAvAKgdc2n64tk4XUZzvTs8VfSUDI+eB9lt4/TRkSBKe/3csEp+/uMVbIP3NN0gVIwWZjuZANZI8khL486CEYwOZ1jbkP097pBKaohT5s+rUWFOozdSsfI4OpjxE1JU3k1SCsJblUNSymjVozuJ5q46lGimJuK3hPzHfEK3pNmpnWg5rZUDyTuV0=
